export {
  OPERATIONAL_HUB_LINKS,
  type OperationalHubLink,
  type OperationalHubSurface,
} from "./hub-nav-config";

export {
  CUSTOMER_VISIBLE_TRUTH_COPY,
  OPERATIONAL_DIGEST_SOURCE_COPY,
  OPERATIONAL_DERIVED_SNAPSHOT_COPY,
  OPERATIONAL_DURABILITY_PRINCIPLES,
  OPERATIONAL_INCIDENT_POSTURE_COPY,
} from "./shared-copy";
